<div class="bar">
    <?php
    $newsCollection = $block->getCollection();
    if ($newsCollection->getSize() > 0) :
        ?>
        <div class="toolbar top">
            <?php echo $block->getPagerHtml(); ?>
        </div>

        <ul>
            <?php foreach ($newsCollection as $news) : ?>
                <li>
                    <div class="bar-list">
                        <a class="news-title" href="<?php echo $this->getUrl('news/index/view',
                            ['id' => $news->getId()]) ?>"><?php echo $news->getTitle() ?></a>
                        <div class="bar-list-content">
                            <?php echo $news->getSummary() ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>

        <div style="clear: both"></div>

        <div class="toolbar-bottom">
            <div class="toolbar bottom">
                <?php echo $block->getPagerHtml(); ?>
            </div>
        </div>
    <?php else : ?>
        <p><?php echo __('Have no article!') ?></p>
    <?php endif; ?>
</div>